import { Check, Edit2, Trash2 } from "lucide-react";
import { NutritionChecklistItem } from "@/lib/nutrition/nutritionChecklistEngine";

interface ChecklistItemProps {
  item: NutritionChecklistItem;
  onToggle: (id: string) => void;
  onEdit: (id: string) => void;
  onDelete: (id: string) => void;
}

export default function ChecklistItem({ item, onToggle, onEdit, onDelete }: ChecklistItemProps) {
  return (
    <div
      className={`flex items-start gap-3 p-4 rounded-xl border transition-all ${
        item.completed
          ? "bg-muted/30 border-border/40 opacity-70"
          : "bg-card border-border shadow-sm hover:shadow-md"
      }`}
    >
      <button
        onClick={() => onToggle(item.id)}
        className={`mt-1 flex-shrink-0 w-6 h-6 rounded-md border-2 flex items-center justify-center transition-colors ${
          item.completed
            ? "bg-primary border-primary text-primary-foreground"
            : "border-muted-foreground/30 hover:border-primary/50 bg-background"
        }`}
      >
        {item.completed && <Check className="w-4 h-4" />}
      </button>

      <div className="flex-1 min-w-0">
        <div className="flex items-start justify-between gap-2">
          <div>
            <h4
              className={`text-sm font-semibold transition-all ${
                item.completed ? "line-through text-muted-foreground" : "text-foreground"
              }`}
            >
              {item.title}
            </h4>
            {item.why && (
              <p className="text-[11px] text-muted-foreground mt-0.5 leading-relaxed">
                {item.why}
              </p>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2 mt-3">
          <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-muted text-muted-foreground">
            {item.category}
          </span>
          <span
            className={`text-[10px] font-medium px-2 py-0.5 rounded-full ${
              item.autoGenerated
                ? "bg-blue-100 text-blue-700 border border-blue-200"
                : "bg-purple-100 text-purple-700 border border-purple-200"
            }`}
          >
            {item.autoGenerated ? "Suggested" : "Custom"}
          </span>
        </div>
      </div>

      <div className="flex items-center gap-1 opacity-60 hover:opacity-100 transition-opacity">
        <button
          onClick={() => onEdit(item.id)}
          className="p-2 hover:bg-muted rounded-lg transition-colors"
          title="Edit"
        >
          <Edit2 className="w-4 h-4 text-muted-foreground" />
        </button>
        <button
          onClick={() => onDelete(item.id)}
          className="p-2 hover:bg-rose-100 rounded-lg transition-colors group"
          title="Delete"
        >
          <Trash2 className="w-4 h-4 text-muted-foreground group-hover:text-rose-600" />
        </button>
      </div>
    </div>
  );
}
