import { useState, useEffect } from "react";
import { usePregnancyProfile } from "@/hooks/usePregnancyProfile";
import { useHealthLog } from "@/hooks/useHealthLog";
import { generateNutritionChecklist, NutritionChecklistItem } from "@/lib/nutrition/nutritionChecklistEngine";
import { predictMaternityDeficiencies } from "@/lib/maternityNutritionEngine";
import ScrollReveal from "@/components/ScrollReveal";
import ChecklistItem from "@/components/nutrition/ChecklistItem";
import ChecklistSummary from "@/components/nutrition/ChecklistSummary";
import AddChecklistModal from "@/components/nutrition/AddChecklistModal";
import DailyHealthChecklist from "@/components/nutrition/DailyHealthChecklist";
import { CheckSquare, Plus, Apple, Lightbulb } from "lucide-react";

const STORAGE_KEY = "mama_haven_nutrition_checklist";

interface NutritionChecklistSectionProps {
  className?: string;
}

export default function NutritionChecklistSection({ className = "" }: NutritionChecklistSectionProps) {
  const { trimester, currentWeek } = usePregnancyProfile();
  const { logs } = useHealthLog();

  const [items, setItems] = useState<NutritionChecklistItem[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<NutritionChecklistItem | null>(null);

  // Initialize and sync checklist
  useEffect(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    let currentItems: NutritionChecklistItem[] = saved ? JSON.parse(saved) : [];

    // Extract symptoms from logs
    const today = new Date().toISOString().split("T")[0];
    const recentLogs = Object.entries(logs)
      .filter(([date]) => new Date(date) >= new Date(Date.now() - 7 * 24 * 60 * 60 * 1000))
      .map(([date, entry]) => entry);
      
    const symptoms = recentLogs.flatMap(log => {
      if (log.phase !== "maternity" || !log.symptoms) return [];
      // log.symptoms is Record<string, boolean> for maternity
      return Object.entries(log.symptoms)
        .filter(([_, isActive]) => isActive)
        .map(([key]) => key);
    });
    // Get deficiencies
    const maternityData = predictMaternityDeficiencies(logs, trimester);
    const deficiencies = maternityData.predictions.map(p => p.nutrient);

    // Generate new suggestions
    const generated = generateNutritionChecklist(trimester, symptoms, deficiencies);

    // Merge: Keep all existing (custom + previously generated that user might have checked off)
    // Add new generated items if they don't exist by title
    const newItems = [...currentItems];
    generated.forEach(genItem => {
      if (!newItems.some(i => i.title.toLowerCase() === genItem.title.toLowerCase())) {
        newItems.push(genItem);
      }
    });

    setItems(newItems);
  }, [trimester, logs]);

  // Save to local storage whenever items change
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
  }, [items]);

  const handleToggle = (id: string) => {
    setItems(items.map(item => 
      item.id === id ? { ...item, completed: !item.completed } : item
    ));
  };

  const handleDelete = (id: string) => {
    setItems(items.filter(item => item.id !== id));
  };

  const handleSaveItem = (itemData: Omit<NutritionChecklistItem, "id" | "autoGenerated" | "completed">) => {
    if (editingItem) {
      setItems(items.map(item => 
        item.id === editingItem.id ? { ...item, ...itemData } : item
      ));
    } else {
      setItems([...items, {
        id: crypto.randomUUID(),
        ...itemData,
        autoGenerated: false,
        completed: false
      }]);
    }
  };

  const openAddModal = () => {
    setEditingItem(null);
    setIsModalOpen(true);
  };

  const openEditModal = (id: string) => {
    const item = items.find(i => i.id === id);
    if (item) {
      setEditingItem(item);
      setIsModalOpen(true);
    }
  };

  const incompleteItems = items.filter(i => !i.completed);
  const completedItems = items.filter(i => i.completed);

  return (
    <div className={className}>
      {/* Section Header */}
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500 to-violet-400 flex items-center justify-center shadow-md">
          <CheckSquare className="w-4 h-4 text-white" />
        </div>
        <div>
          <h2 className="text-base font-bold">Nutrition Checklist</h2>
          <p className="text-[11px] text-muted-foreground">
            Smart nutrition actions personalized for your pregnancy journey
          </p>
        </div>
      </div>

      <ScrollReveal>
        <ChecklistSummary items={items} />
      </ScrollReveal>

      <ScrollReveal delay={100}>
        <DailyHealthChecklist currentWeek={currentWeek} />
      </ScrollReveal>

      <ScrollReveal delay={200}>
        <div className="flex items-center justify-between mb-4 mt-6">
          <div className="flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-purple-600" />
            <h3 className="text-sm font-bold">Today's Focus</h3>
          </div>
          <button
            onClick={openAddModal}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-primary text-primary-foreground rounded-lg text-xs font-medium hover:bg-primary/90 transition-colors"
          >
            <Plus className="w-3.5 h-3.5" />
            Add Task
          </button>
        </div>

        <div className="space-y-3">
          {incompleteItems.length === 0 ? (
            <div className="text-center py-10 bg-card rounded-xl border border-dashed">
              <Apple className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
              <p className="text-muted-foreground text-sm">All caught up! Add a custom task or check back later.</p>
            </div>
          ) : (
            incompleteItems.map(item => (
              <ChecklistItem
                key={item.id}
                item={item}
                onToggle={handleToggle}
                onEdit={openEditModal}
                onDelete={handleDelete}
              />
            ))
          )}
        </div>
      </ScrollReveal>

      {completedItems.length > 0 && (
        <ScrollReveal delay={300}>
          <h3 className="text-sm font-bold mb-4 mt-6 flex items-center gap-2 text-muted-foreground">
            <CheckSquare className="w-4 h-4" />
            Completed Summary
          </h3>
          <div className="space-y-3">
            {completedItems.map(item => (
              <ChecklistItem
                key={item.id}
                item={item}
                onToggle={handleToggle}
                onEdit={openEditModal}
                onDelete={handleDelete}
              />
            ))}
          </div>
        </ScrollReveal>
      )}

      <AddChecklistModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSave={handleSaveItem}
        initialData={editingItem}
      />
    </div>
  );
}
