export interface WeekData {
  week: number;
  trimester: 1 | 2 | 3;
  babySize: string;
  babySizeEmoji: string;
  development: string;
  momFeels: string;
  nutritionTips: string[];
  hygieneTips: string[];
  activityTips: string[];
  warningSigns: string[];
}

export const WEEK_DATA: WeekData[] = [
  { week: 1, trimester: 1, babySize: "Poppy seed", babySizeEmoji: "🌱", development: "Fertilization occurs. The fertilized egg begins dividing rapidly.", momFeels: "You may not feel any changes yet. Your body is preparing for pregnancy.", nutritionTips: ["Start folic acid (400 mcg daily)", "Eat iron-rich foods like spinach and lentils", "Stay hydrated — 8-10 glasses of water"], hygieneTips: ["Wash hands frequently", "Avoid raw or undercooked food", "Maintain oral hygiene"], activityTips: ["Continue normal activities", "Start gentle walking daily", "Get adequate sleep (7-9 hours)"], warningSigns: ["Heavy bleeding", "Severe abdominal pain"] },
  { week: 2, trimester: 1, babySize: "Poppy seed", babySizeEmoji: "🌱", development: "The egg implants in the uterine wall. Hormonal changes begin.", momFeels: "Light spotting possible. Mild cramping similar to period cramps.", nutritionTips: ["Continue folic acid", "Add calcium-rich foods (milk, curd, ragi)", "Eat green leafy vegetables daily"], hygieneTips: ["Avoid exposure to chemicals", "Use mild, unscented soap", "Keep nails trimmed and clean"], activityTips: ["Yoga and stretching", "Avoid heavy lifting", "Practice deep breathing"], warningSigns: ["Heavy bleeding with clots", "Severe pain on one side"] },
  { week: 3, trimester: 1, babySize: "Poppy seed", babySizeEmoji: "🌱", development: "The embryo begins to form. Neural tube development starts.", momFeels: "Breast tenderness may begin. Fatigue is common.", nutritionTips: ["Eat protein-rich food (dal, eggs, paneer)", "Include fruits daily", "Avoid raw papaya and pineapple"], hygieneTips: ["Boil drinking water", "Wash vegetables thoroughly", "Avoid mosquito bites (use safe repellent)"], activityTips: ["Short walks after meals", "Pelvic floor exercises", "Rest when tired"], warningSigns: ["Severe nausea preventing eating", "High fever"] },
  { week: 4, trimester: 1, babySize: "Sesame seed", babySizeEmoji: "🫘", development: "The heart begins to beat. Brain, spinal cord forming.", momFeels: "Morning sickness may start. Heightened sense of smell. Mood swings.", nutritionTips: ["Small frequent meals to manage nausea", "Ginger tea for morning sickness", "Iron supplements as prescribed"], hygieneTips: ["Regular bathing", "Wear comfortable cotton clothes", "Good dental care (pregnancy gingivitis prevention)"], activityTips: ["Gentle stretching", "Avoid contact sports", "Meditation for 10 minutes daily"], warningSigns: ["Severe vomiting (can't keep food down)", "Spotting with pain"] },
  { week: 5, trimester: 1, babySize: "Lentil", babySizeEmoji: "🫘", development: "Major organs begin forming. Tiny arm and leg buds appear.", momFeels: "Fatigue increases. Frequent urination. Nausea may intensify.", nutritionTips: ["Eat whole grains (roti, brown rice)", "Coconut water for hydration", "Avoid excessive caffeine"], hygieneTips: ["Change undergarments daily", "Use cotton fabric", "Avoid strong perfumes"], activityTips: ["Prenatal yoga", "Walking 20 minutes", "Kegel exercises begin"], warningSigns: ["Bleeding with cramps", "Severe headache with vision changes"] },
  { week: 6, trimester: 1, babySize: "Sweet pea", babySizeEmoji: "🌿", development: "Facial features forming. Heart beats 100-160 times per minute.", momFeels: "Morning sickness peaks. Food aversions common. Bloating.", nutritionTips: ["Crackers before getting up for nausea", "Vitamin B6 foods (banana, chickpeas)", "Buttermilk (chaas) for digestion"], hygieneTips: ["Wash fruits before eating", "Avoid unpasteurized dairy", "Regular handwashing"], activityTips: ["Swimming (if available)", "Gentle stretching", "Avoid lying flat on back for long"], warningSigns: ["Sharp pelvic pain", "Heavy bleeding"] },
  { week: 7, trimester: 1, babySize: "Blueberry", babySizeEmoji: "🫐", development: "Brain grows rapidly. Arms and legs lengthening.", momFeels: "Acne possible due to hormones. Excessive saliva. Constipation.", nutritionTips: ["High-fiber foods (oats, fruits with skin)", "Probiotic foods (curd, idli)", "Stay very hydrated"], hygieneTips: ["Gentle face wash for acne", "Wear comfortable bras", "Oral hygiene important"], activityTips: ["Prenatal exercises", "Avoid jumping or bouncing", "Rest between activities"], warningSigns: ["Fever above 100.4°F", "Painful urination"] },
  { week: 8, trimester: 1, babySize: "Raspberry", babySizeEmoji: "🍇", development: "Fingers and toes forming. Baby starts moving (too small to feel).", momFeels: "Breasts growing. Vivid dreams. Mild cramping normal.", nutritionTips: ["Omega-3 foods (walnuts, flaxseed)", "Seasonal fruits", "Avoid junk food and sodas"], hygieneTips: ["Use sunscreen (pregnancy pigmentation)", "Cotton undergarments", "Clean sleeping area"], activityTips: ["Daily walk 15-20 min", "Breathing exercises", "Avoid saunas and hot baths"], warningSigns: ["Sudden severe cramping", "Fainting or dizziness"] },
  { week: 9, trimester: 1, babySize: "Cherry", babySizeEmoji: "🍒", development: "All essential organs formed. Tail disappears. Looks more human.", momFeels: "Waistline may expand. Heartburn beginning. Emotional ups and downs.", nutritionTips: ["Small meals every 2-3 hours", "Avoid spicy food if heartburn", "Jaggery for iron (moderate)"], hygieneTips: ["Elevate head while sleeping for heartburn", "Wear loose clothing", "Regular oil massage (coconut/sesame)"], activityTips: ["Moderate walking", "Prenatal dance", "Avoid intense workouts"], warningSigns: ["Vaginal discharge with bad odor", "Severe abdominal pain"] },
  { week: 10, trimester: 1, babySize: "Kumquat", babySizeEmoji: "🍊", development: "Bones and cartilage forming. Vital organs functioning.", momFeels: "Less nausea for some. Visible veins. Growing belly.", nutritionTips: ["Calcium (milk, ragi, sesame seeds)", "Vitamin D (morning sun 15 min)", "Green vegetables daily"], hygieneTips: ["Moisturize skin to prevent stretch marks", "Maintain oral health", "Clean food preparation area"], activityTips: ["Squats (supported)", "Pelvic tilts", "Light housework OK"], warningSigns: ["Heavy bleeding", "Severe headache"] },
  { week: 11, trimester: 1, babySize: "Fig", babySizeEmoji: "🍐", development: "Baby can open and close fists. Tooth buds appearing.", momFeels: "Energy slowly returning. Hair may thicken. Bloating reduces.", nutritionTips: ["Protein at every meal", "Nuts and seeds for snacking", "Amla for Vitamin C"], hygieneTips: ["Safe insect repellent use", "Hand hygiene before eating", "Proper food storage"], activityTips: ["Prenatal Pilates", "Walking 30 min", "Pelvic floor exercises"], warningSigns: ["Sudden swelling of face/hands", "Blurred vision"] },
  { week: 12, trimester: 1, babySize: "Lime", babySizeEmoji: "🍋", development: "Reflexes developing. Baby can suck thumb. Gender organs forming.", momFeels: "Morning sickness easing. Bump becoming visible. More energy.", nutritionTips: ["Balanced thali approach", "Include all food groups", "IFA tablets as prescribed"], hygieneTips: ["Regular prenatal checkups", "Dental checkup recommended", "Comfortable footwear"], activityTips: ["Resume light exercise if paused", "Swimming", "Relaxation techniques"], warningSigns: ["Any bleeding at this stage", "Persistent high fever"] },
  { week: 13, trimester: 2, babySize: "Peach", babySizeEmoji: "🍑", development: "Baby can make facial expressions. Vocal cords developing.", momFeels: "Second trimester glow! Energy boost. Appetite increases.", nutritionTips: ["Increase calorie intake by 300 cal/day", "Iron-rich foods (dates, pomegranate)", "Whole grain chapatis"], hygieneTips: ["Stretch mark prevention cream", "Supportive bra", "Safe travel precautions"], activityTips: ["Walking daily 30 min", "Prenatal yoga", "Aqua exercises"], warningSigns: ["Persistent headache", "Sudden weight gain"] },
  { week: 14, trimester: 2, babySize: "Lemon", babySizeEmoji: "🍋", development: "Brain impulses firing. Baby making expressions. Kidney producing urine.", momFeels: "Less bathroom trips. Thicker hair. May feel round ligament pain.", nutritionTips: ["Drumstick (moringa) leaves for iron", "Coconut in cooking", "Fresh fruit juices (no added sugar)"], hygieneTips: ["Side sleeping position", "Body pillow for comfort", "Regular bathing"], activityTips: ["Moderate exercise OK", "Avoid lying flat on back", "Stretching morning and evening"], warningSigns: ["Watery vaginal discharge", "Fever with body aches"] },
  { week: 15, trimester: 2, babySize: "Apple", babySizeEmoji: "🍎", development: "Bones ossifying. Baby can sense light through closed eyelids.", momFeels: "Nasal congestion common. Gums may bleed. Growing bump.", nutritionTips: ["Citrus fruits for Vitamin C", "Mixed dal for complete protein", "Ghee in moderation (good fats)"], hygieneTips: ["Gentle nose care", "Soft toothbrush for gums", "Wear comfortable shoes"], activityTips: ["Prenatal exercise classes", "Swimming", "Avoid heavy lifting"], warningSigns: ["Burning urination", "Severe back pain"] },
  { week: 16, trimester: 2, babySize: "Avocado", babySizeEmoji: "🥑", development: "Muscles developing. Baby moving actively. Can hear sounds.", momFeels: "May feel first flutters (quickening)! Backache may start.", nutritionTips: ["DHA foods (walnuts, flaxseed oil)", "Banana for potassium", "Turmeric milk (haldi doodh) at night"], hygieneTips: ["Support belt for back pain", "Correct posture while sitting", "Warm (not hot) showers"], activityTips: ["Pelvic tilts for back pain", "Cat-cow yoga pose", "Walking continues"], warningSigns: ["Reduced fetal movement (if felt before)", "Severe itching"] },
  { week: 17, trimester: 2, babySize: "Pear", babySizeEmoji: "🍐", development: "Fat layer forming. Fingerprints developing. Sweat glands forming.", momFeels: "Increased appetite. Vivid dreams. Better mood overall.", nutritionTips: ["Paneer/tofu for protein", "Sweet potato for Vitamin A", "Avoid excess salt"], hygieneTips: ["Apply coconut oil on belly", "Comfortable maternity clothes", "Foot elevation for swelling"], activityTips: ["Squats with support", "Kegel exercises daily", "Relaxation music"], warningSigns: ["Persistent vomiting", "Swelling with headache"] },
  { week: 18, trimester: 2, babySize: "Bell pepper", babySizeEmoji: "🫑", development: "Baby hears your heartbeat. Nervous system maturing.", momFeels: "Definite baby movements felt. Leg cramps at night. Growing belly.", nutritionTips: ["Magnesium food for cramps (banana, dark chocolate)", "Ragi porridge", "Plenty of fluids"], hygieneTips: ["Leg stretches before sleep", "Warm massage for cramps", "Proper pillow support"], activityTips: ["Prenatal yoga flow", "Gentle back exercises", "Avoid standing for long"], warningSigns: ["No movement felt by week 20", "Bleeding or spotting"] },
  { week: 19, trimester: 2, babySize: "Mango", babySizeEmoji: "🥭", development: "Vernix covering baby's skin. Brain designating sensory areas.", momFeels: "Hip pain possible. Skin changes (linea nigra). Good energy.", nutritionTips: ["Seasonal fruits and vegetables", "Sprouts for protein", "Curd rice for comfort"], hygieneTips: ["Stay cool — avoid overheating", "Moisturize skin regularly", "Safe sleeping position (left side best)"], activityTips: ["Swimming excellent this trimester", "Prenatal dance", "Hip stretches"], warningSigns: ["Sudden swelling", "Severe headache with spots"] },
  { week: 20, trimester: 2, babySize: "Banana", babySizeEmoji: "🍌", development: "Halfway mark! Anatomy scan week. Baby swallows amniotic fluid.", momFeels: "Belly button may pop. Breathlessness with exertion. Itchy skin.", nutritionTips: ["Mid-pregnancy nutrition boost", "Mixed nuts handful daily", "Hydrate with nimbu paani"], hygieneTips: ["Attend anomaly scan", "Track baby movements", "Comfortable sleep positions"], activityTips: ["Continue moderate exercise", "Birth prep reading", "Meditation 15 min"], warningSigns: ["No fetal movement", "Fluid leaking from vagina"] },
  { week: 21, trimester: 2, babySize: "Carrot", babySizeEmoji: "🥕", development: "Baby's movements become more coordinated. Taste buds forming.", momFeels: "Increased vaginal discharge (normal). Varicose veins possible.", nutritionTips: ["Fiber for constipation (oats, fruits)", "Probiotic foods", "Adequate water intake"], hygieneTips: ["Cotton undergarments changed frequently", "Leg elevation", "Compression stockings if needed"], activityTips: ["Walking 30-45 min", "Prenatal classes", "Breathing exercises"], warningSigns: ["Severe itching all over", "Regular contractions this early"] },
  { week: 22, trimester: 2, babySize: "Papaya", babySizeEmoji: "🍈", development: "Eyes formed (but irises lack color). Grip strengthening.", momFeels: "Stretch marks may appear. Appetite strong. Ankle swelling.", nutritionTips: ["Vitamin E foods (almonds, sunflower seeds)", "Adequate protein (75-100g/day)", "Limit fried foods"], hygieneTips: ["Bio-oil or coconut oil for stretch marks", "Comfortable maternity wear", "Keep feet elevated"], activityTips: ["Water aerobics", "Gentle yoga", "Avoid heavy exercises"], warningSigns: ["Severe back pain with fever", "Persistent contractions"] },
  { week: 23, trimester: 2, babySize: "Grapefruit", babySizeEmoji: "🍊", development: "Lungs practicing breathing. Hearing well developed.", momFeels: "Swollen feet in evening. Practice contractions may start. Forgetfulness.", nutritionTips: ["Berries for antioxidants", "Continued iron supplementation", "Warm soups and broths"], hygieneTips: ["Foot soak in warm water", "Rest with legs elevated", "Track blood pressure at home"], activityTips: ["Modify exercises as belly grows", "Birthing ball exercises", "Avoid supine exercises"], warningSigns: ["Severe swelling (preeclampsia sign)", "Visual disturbances"] },
  { week: 24, trimester: 2, babySize: "Corn on the cob", babySizeEmoji: "🌽", development: "Baby is viable outside womb with medical care. Lungs maturing.", momFeels: "Energy may dip. Glucose test week. Skin pigmentation.", nutritionTips: ["Prepare for glucose test (eat normally)", "Complex carbs preferred", "Avoid sugary drinks"], hygieneTips: ["Glucose tolerance test this week", "Regular BP monitoring", "Skin care for pigmentation"], activityTips: ["Prenatal exercises continue", "Hospital bag planning", "Rest when needed"], warningSigns: ["Sugar in urine", "Sudden weight gain"] },
  { week: 25, trimester: 2, babySize: "Cauliflower", babySizeEmoji: "🥦", development: "Baby responds to voice. Hair growing. Breathing motions.", momFeels: "Heartburn returns. Hemorrhoids possible. Carpal tunnel.", nutritionTips: ["Small frequent meals for heartburn", "Fennel water (saunf)", "Warm milk at bedtime"], hygieneTips: ["Elevated sleeping for heartburn", "Regular gentle exercise for hemorrhoids", "Wrist exercises for carpal tunnel"], activityTips: ["Modified prenatal yoga", "Gentle walks", "Hand and wrist stretches"], warningSigns: ["Bright red bleeding", "Reduced fetal movement"] },
  { week: 26, trimester: 2, babySize: "Lettuce head", babySizeEmoji: "🥬", development: "Eyes opening. Brain waves detectable. Immune system building.", momFeels: "Trouble sleeping. Baby very active. Leg cramps at night.", nutritionTips: ["Calcium before bed for cramps", "Warm chamomile tea", "Light dinner early evening"], hygieneTips: ["Pregnancy pillow for sleep", "Night light for bathroom trips", "Stretching before bed"], activityTips: ["Sleep hygiene routine", "Relaxation exercises", "Gentle daily movement"], warningSigns: ["Leaking fluid", "Regular contractions before 37 weeks"] },
  { week: 27, trimester: 3, babySize: "Eggplant", babySizeEmoji: "🍆", development: "Third trimester begins! Baby can open eyes. Regular sleep-wake cycle.", momFeels: "Shortness of breath. Practice contractions more frequent. Nesting instinct.", nutritionTips: ["Iron-rich foods intensified", "Small meals for breathlessness", "Dates from week 36 onward (plan ahead)"], hygieneTips: ["Hospital bag preparation", "Birth plan discussion", "Regular prenatal visits now biweekly"], activityTips: ["Walking most comfortable exercise", "Birth preparation classes", "Perineal massage beginning"], warningSigns: ["Regular painful contractions", "Fluid gush from vagina"] },
  { week: 28, trimester: 3, babySize: "Coconut", babySizeEmoji: "🥥", development: "Baby dreaming (REM sleep). Rapid brain growth. Can hiccup.", momFeels: "Kick counts start. Back pain worsens. Frequent urination returns.", nutritionTips: ["Continue balanced diet", "Extra protein for baby growth", "Hydration crucial"], hygieneTips: ["Daily kick count monitoring", "Cold compress for back pain", "Maternity belt support"], activityTips: ["Birthing ball sitting", "Hip circles", "Pelvic floor exercises daily"], warningSigns: ["Less than 10 kicks in 2 hours", "Persistent headache"] },
  { week: 29, trimester: 3, babySize: "Butternut squash", babySizeEmoji: "🎃", development: "Muscles and lungs maturing. Baby gaining weight rapidly.", momFeels: "Breathless going upstairs. Heartburn intense. Emotional preparation.", nutritionTips: ["Iron and calcium still priority", "Antioxidant-rich berries and fruits", "Limit salt for swelling"], hygieneTips: ["Comfortable sleeping aids", "Regular movement every hour", "Monitor swelling daily"], activityTips: ["Short walks multiple times", "Prenatal breathing", "Relaxation visualization"], warningSigns: ["Sudden severe headache", "Vision changes", "Severe upper belly pain"] },
  { week: 30, trimester: 3, babySize: "Cabbage", babySizeEmoji: "🥬", development: "Baby's brain growing fast. Lanugo hair disappearing.", momFeels: "10 weeks to go! Pelvis pressure. Sleep disruptions.", nutritionTips: ["Complex carbs for sustained energy", "Fruits with meals", "Adequate fluids (avoid before bed)"], hygieneTips: ["Prenatal checkups every 2 weeks", "Blood pressure monitoring", "Weight tracking"], activityTips: ["Modified yoga only", "Birthing positions practice", "Relaxation and rest"], warningSigns: ["Water breaking (clear fluid)", "Decreased movement"] },
  { week: 31, trimester: 3, babySize: "Pineapple", babySizeEmoji: "🍍", development: "All five senses working. Baby processing information. Fat layer thickening.", momFeels: "Waddling walk. Frequent practice contractions. Nesting urge strong.", nutritionTips: ["Energy-dense healthy foods", "Dates (2-3 daily from now)", "Warm turmeric milk"], hygieneTips: ["Hospital bag ready", "Birth plan finalized", "Emergency contacts updated"], activityTips: ["Very gentle walking", "Birthing ball", "Deep breathing practice"], warningSigns: ["Regular contractions < 37 weeks", "Bleeding", "Reduced movement"] },
  { week: 32, trimester: 3, babySize: "Jicama", babySizeEmoji: "🥔", development: "Baby head-down in most cases. Toenails grown. Practicing breathing.", momFeels: "Heartburn peak. Difficulty bending. Baby kicks visible from outside.", nutritionTips: ["Small meals every 2-3 hours", "Avoid lying down after eating", "Fennel and ginger for digestion"], hygieneTips: ["Good posture important", "Supportive footwear", "Rest frequently"], activityTips: ["Short slow walks", "Pelvic tilts for comfort", "Relaxation techniques"], warningSigns: ["Baby not head-down (discuss with doctor)", "Severe swelling"] },
  { week: 33, trimester: 3, babySize: "Celery bunch", babySizeEmoji: "🥬", development: "Immune system developing. Bones hardening (skull stays soft).", momFeels: "Overheating. Pelvic girdle pain. Very active baby.", nutritionTips: ["Continue iron-rich foods", "Light hydrating foods", "Cooling foods (cucumber, watermelon)"], hygieneTips: ["Stay cool — wear loose cotton", "Gentle pelvic support exercises", "Monitor for preeclampsia signs"], activityTips: ["Movement as tolerated", "Birth positions review", "Mental preparation"], warningSigns: ["Headache + swelling + high BP", "Decreased fetal movement"] },
  { week: 34, trimester: 3, babySize: "Cantaloupe", babySizeEmoji: "🍈", development: "Central nervous system maturing. Fat layer for temperature regulation.", momFeels: "Exhaustion. Cervix may start softening. Frequent bathroom trips.", nutritionTips: ["Complex carbs and protein for stamina", "Dates (6 per day from week 36)", "Stay hydrated always"], hygieneTips: ["Weekly prenatal checkups start", "NST test if advised", "Perineal massage"], activityTips: ["Rest is important now", "Gentle movement only", "Practice labor breathing"], warningSigns: ["Painful regular contractions", "Leaking fluid", "Baby not moving"] },
  { week: 35, trimester: 3, babySize: "Honeydew melon", babySizeEmoji: "🍈", development: "Kidneys fully developed. Liver can process waste. Baby is plump.", momFeels: "Difficulty sleeping. Lightning crotch. Heavy belly.", nutritionTips: ["Light, nutritious meals", "Keep hydrated", "Energy bars for labor bag"], hygieneTips: ["Pack labor bag items", "Keep ID and documents ready", "Plan transport to hospital"], activityTips: ["Birthing ball daily", "Relaxation and visualization", "Sleep whenever possible"], warningSigns: ["Water breaking", "Bloody show (may be normal — confirm with doctor)"] },
  { week: 36, trimester: 3, babySize: "Romaine lettuce", babySizeEmoji: "🥬", development: "Baby drops into pelvis (lightening). Meconium forming in intestines.", momFeels: "Easier to breathe! More pelvic pressure. Frequent urination extreme.", nutritionTips: ["6 dates per day (studies show benefits for labor)", "Light meals — room for stomach now", "Red raspberry leaf tea (ask doctor first)"], hygieneTips: ["Weekly doctor visits", "GBS test this week", "Hospital pre-registration"], activityTips: ["Walking helps baby descend", "Squats with support", "Perineal massage daily"], warningSigns: ["Contractions < 5 min apart", "Water breaking", "Reduced movements"] },
  { week: 37, trimester: 3, babySize: "Watermelon", babySizeEmoji: "🍉", development: "Baby is early term! Fully developed. Practicing swallowing and breathing.", momFeels: "Nesting urge peak. Cervix dilating slowly. Mucus plug may pass.", nutritionTips: ["Continue dates", "Light, easily digestible food", "Hydration priority"], hygieneTips: ["Know the signs of labor", "Hospital bag at door", "Keep phone charged"], activityTips: ["Walking and bouncing on birth ball", "Rest between activities", "Labor position practice"], warningSigns: ["Heavy bleeding", "Decreased movement", "Severe headache or vision changes"] },
  { week: 38, trimester: 3, babySize: "Pumpkin", babySizeEmoji: "🎃", development: "Brain and lungs continue maturing. Baby shedding lanugo and vernix.", momFeels: "Could go into labor anytime! Practice contractions very frequent. Exhaustion.", nutritionTips: ["Light meals — labor could start", "Keep snacking for energy", "Coconut water for electrolytes"], hygieneTips: ["Watch for labor signs", "Bag, documents, plan ready", "Rest as much as possible"], activityTips: ["Walking if comfortable", "Rest is priority", "Practice breathing for labor"], warningSigns: ["Contractions 5 min apart lasting 1 min for 1 hour (5-1-1 rule)", "Water breaking"] },
  { week: 39, trimester: 3, babySize: "Small watermelon", babySizeEmoji: "🍉", development: "Baby fully term! Adding fat for temperature regulation after birth.", momFeels: "Very heavy. Impatient! Cervix ripening. Nesting continues.", nutritionTips: ["Eat when hungry", "Energy-rich snacks", "Stay hydrated"], hygieneTips: ["Final checks — hospital route planned", "Emergency contacts on speed dial", "Rest and stay calm"], activityTips: ["Gentle walking", "Stair climbing (if comfortable)", "Nipple stimulation (ask doctor)"], warningSigns: ["Decreased movement", "Heavy bleeding", "Severe headache"] },
  { week: 40, trimester: 3, babySize: "Watermelon", babySizeEmoji: "🍉", development: "Due date week! Baby is ready. Average size 7.5 lbs, 20 inches.", momFeels: "Could go into labor anytime or may go past due date (normal).", nutritionTips: ["Continue normal eating", "Spicy food myth — no evidence but safe", "Energy for labor"], hygieneTips: ["Doctor will discuss induction if needed", "Monitor movement carefully", "Stay calm and positive"], activityTips: ["Walking helps labor start naturally", "Relaxation is key", "Labor breathing practice"], warningSigns: ["No movement for 2+ hours", "Heavy bleeding", "Signs of infection (fever, discharge)"] },
];

export function getCurrentWeek(dueDate: string): number {
  const due = new Date(dueDate);
  const now = new Date();
  const totalDays = 280; // 40 weeks
  const daysLeft = Math.ceil((due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
  const daysPassed = totalDays - daysLeft;
  const week = Math.max(1, Math.min(40, Math.ceil(daysPassed / 7)));
  return week;
}

export function getDaysRemaining(dueDate: string): number {
  const due = new Date(dueDate);
  const now = new Date();
  return Math.max(0, Math.ceil((due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)));
}

export function getTrimester(week: number): 1 | 2 | 3 {
  if (week <= 12) return 1;
  if (week <= 26) return 2;
  return 3;
}

export function getProgressPercentage(week: number): number {
  return Math.min(100, Math.round((week / 40) * 100));
}
