

export interface NutritionChecklistItem {
  id: string;
  title: string;
  category: string;
  autoGenerated: boolean;
  completed: boolean;
  why?: string;
}

export function generateNutritionChecklist(
  trimester: number | null,
  symptoms: string[],
  deficiencies: string[] = []
): NutritionChecklistItem[] {
  const checklist: NutritionChecklistItem[] = [];
  const add = (title: string, category: string, why: string) => {
    // Only add if we don't already have a very similar item
    if (!checklist.some((item) => item.title.toLowerCase() === title.toLowerCase())) {
      checklist.push({
        id: crypto.randomUUID(),
        title,
        category,
        autoGenerated: true,
        completed: false,
        why,
      });
    }
  };

  // Base hydration for all
  add("Drink 2.5L Water", "Hydration", "Essential for amniotic fluid and blood volume");
  add("Take prenatal vitamin", "Supplements", "Daily nutritional support");

  // Trimester specific
  if (trimester === 1) {
    add("Add folate-rich foods (spinach, lentils)", "Nutrients", "Crucial for neural tube development");
  } else if (trimester === 2) {
    add("Increase calcium-rich meals", "Bone Health", "Supports baby's growing bones");
    add("Add iron-rich foods", "Energy", "Prevents anemia as blood volume increases");
  } else if (trimester === 3) {
    add("Eat smaller, frequent meals", "Digestion", "Helps manage heartburn and feeling full");
    add("Stay hydrated but reduce evening fluids", "Hydration", "Reduces nighttime waking");
  }

  // Symptom based
  const lowerSymptoms = symptoms.map(s => s.toLowerCase());
  
  if (lowerSymptoms.includes("nausea") || lowerSymptoms.includes("morning sickness")) {
    add("Drink small frequent fluids", "Hydration", "Helps manage nausea");
    add("Avoid greasy meals", "Digestion", "Easier on your stomach");
    add("Add ginger-based foods or tea", "Relief", "Natural nausea remedy");
  }

  if (lowerSymptoms.includes("fatigue")) {
    add("Increase protein snacks", "Energy", "Sustained energy throughout the day");
    add("Add iron-rich foods", "Energy", "Combat fatigue from low iron");
  }

  if (lowerSymptoms.includes("heartburn") || lowerSymptoms.includes("acid reflux")) {
    add("Avoid spicy foods", "Digestion", "Prevents heartburn triggers");
    add("Avoid late-night eating", "Digestion", "Allows time for digestion before sleep");
    add("Reduce caffeine", "Hydration", "Can worsen acid reflux");
  }

  if (lowerSymptoms.includes("swelling") || lowerSymptoms.includes("water retention")) {
    add("Reduce sodium intake", "Diet", "Helps minimize water retention");
    add("Increase potassium foods (bananas, potatoes)", "Diet", "Balances fluids");
    add("Maintain hydration", "Hydration", "Drinking water actually reduces swelling");
  }
  
  if (lowerSymptoms.includes("constipation")) {
    add("Increase fiber (fruits, veggies, whole grains)", "Digestion", "Promotes regular bowel movements");
  }

  // Deficiencies
  const lowerDeficiencies = deficiencies.map(d => d.toLowerCase());
  if (lowerDeficiencies.includes("iron")) {
    add("Eat spinach and dark leafy greens", "Nutrients", "Plant-based iron source");
    add("Pair iron with vitamin C", "Nutrients", "Enhances iron absorption");
  }
  if (lowerDeficiencies.includes("protein")) {
    add("Add eggs, paneer, or tofu", "Nutrients", "High quality protein sources");
    add("Increase legumes", "Nutrients", "Great plant-based protein");
  }

  return checklist;
}
