import { useMemo, useCallback } from "react";
import { ShieldCheck, Heart, AlertTriangle, FileText, Download, Bone, Droplets, Sparkles, Activity } from "lucide-react";
import { cn } from "@/lib/utils";
import { useMenopause, getStageLabel } from "@/hooks/useMenopause";

// ─── Section Card Component ─────────────────────────────────────────────────

function SectionCard({
  emoji, title, children, prominent, danger, className,
}: {
  emoji: string; title: string; children: React.ReactNode; prominent?: boolean; danger?: boolean; className?: string;
}) {
  return (
    <div className={cn(
      "bg-white rounded-2xl border shadow-sm p-5 transition-all hover:shadow-md",
      danger ? "border-red-300 ring-1 ring-red-100" :
      prominent ? "border-amber-300 ring-1 ring-amber-100" :
      "border-slate-200",
      className
    )}>
      <div className="flex items-center gap-2 mb-3">
        <span className="text-2xl">{emoji}</span>
        <h3 className={cn(
          "text-sm font-bold",
          danger ? "text-red-800" : "text-slate-800"
        )}>{title}</h3>
      </div>
      {children}
    </div>
  );
}

// ─── Doctor Prep PDF Generator ───────────────────────────────────────────────

function generateDoctorPrepText(
  profile: ReturnType<typeof useMenopause>["profile"],
  logs: ReturnType<typeof useMenopause>["logs"]
): string {
  if (!profile) return "";

  const now = new Date();
  const thirtyDaysAgo = new Date(now);
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  const recentLogs = logs.filter((l) => l.date >= thirtyDaysAgo.toISOString().slice(0, 10));

  let text = "═══════════════════════════════════════\n";
  text += "   SwasthyaSakhi — Symptom Summary\n";
  text += "   Prepared for Doctor Visit\n";
  text += `   Date: ${now.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}\n`;
  text += "═══════════════════════════════════════\n\n";

  text += `STAGE: ${getStageLabel(profile.stage)}\n`;
  text += `Last Period: ${profile.lastPeriodDate || "N/A"}\n`;
  text += `Period Regularity: ${profile.periodRegularity}\n`;
  text += `Diet Type: ${profile.diet}\n`;
  text += `On HRT: ${profile.onHRT ? "Yes" : "No"}${profile.hrtDetails ? ` — ${profile.hrtDetails}` : ""}\n`;
  text += `Conditions: ${profile.conditions.length > 0 ? profile.conditions.join(", ") : "None reported"}\n`;
  text += `Family History: ${profile.familyHistory.length > 0 ? profile.familyHistory.join(", ") : "None reported"}\n\n`;

  text += "── SYMPTOM PROFILE (from onboarding) ──\n";
  const syms = profile.symptoms;
  const entries: [string, number][] = [
    ["Hot Flashes", syms.hotFlashes], ["Night Sweats", syms.nightSweats],
    ["Sleep Problems", syms.sleep], ["Fatigue", syms.fatigue],
    ["Mood Swings", syms.moodSwings], ["Anxiety/Stress", syms.anxiety],
    ["Brain Fog", syms.brainFog], ["Joint Pain", syms.jointPain],
    ["Headache", syms.headache],
  ];
  for (const [name, val] of entries) {
    const bar = "█".repeat(val) + "░".repeat(5 - val);
    text += `  ${name.padEnd(16)} ${bar} ${val}/5\n`;
  }
  text += "\n";

  if (recentLogs.length > 0) {
    text += `── LAST 30 DAYS LOG (${recentLogs.length} days logged) ──\n`;
    const avgHF = recentLogs.reduce((s, l) => s + l.hotFlashCount, 0) / recentLogs.length;
    const avgMood = recentLogs.reduce((s, l) => s + l.mood, 0) / recentLogs.length;
    const avgSleep = recentLogs.reduce((s, l) => s + l.sleepHrs, 0) / recentLogs.length;
    const avgPain = recentLogs.reduce((s, l) => s + l.painLevel, 0) / recentLogs.length;
    const periodDays = recentLogs.filter((l) => l.periodOccurred).length;

    text += `  Avg Hot Flashes/day:  ${avgHF.toFixed(1)}\n`;
    text += `  Avg Mood (1-5):       ${avgMood.toFixed(1)}\n`;
    text += `  Avg Sleep (hours):    ${avgSleep.toFixed(1)}\n`;
    text += `  Avg Pain (1-5):       ${avgPain.toFixed(1)}\n`;
    if (profile.stage === "perimenopause") {
      text += `  Period days:          ${periodDays}\n`;
    }
    text += "\n";

    text += "── DAILY LOG DETAIL ──\n";
    text += "  Date       | HF | Mood | Sleep | Pain | Notes\n";
    text += "  -----------|-------|------|-------|------|------\n";
    const sorted = [...recentLogs].sort((a, b) => a.date.localeCompare(b.date));
    for (const log of sorted.slice(-14)) { // last 14 days
      text += `  ${log.date} |  ${String(log.hotFlashCount).padStart(2)}  |  ${log.mood}   |  ${String(log.sleepHrs).padStart(4)} |   ${log.painLevel}  | ${(log.notes || "-").slice(0, 30)}\n`;
    }
  } else {
    text += "── No daily logs recorded in the last 30 days ──\n";
  }

  text += "\n═══════════════════════════════════════\n";
  text += "  Generated by SwasthyaSakhi\n";
  text += "  This is NOT a medical diagnosis.\n";
  text += "  Please share with your healthcare provider.\n";
  text += "═══════════════════════════════════════\n";

  return text;
}

// ─── Main Component ──────────────────────────────────────────────────────────

export default function MenopauseCareEssentials() {
  const { profile, logs } = useMenopause();

  const isPostmenopause = profile?.stage === "postmenopause";
  const hasHypertension = profile?.conditions.includes("hypertension");

  const handleDownloadSummary = useCallback(() => {
    const text = generateDoctorPrepText(profile, logs);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `menopause-summary-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [profile, logs]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50/80 via-white to-orange-50/60">
      <div className="max-w-2xl mx-auto px-4 py-6 md:py-10">
        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center shadow-md shadow-amber-200">
            <ShieldCheck className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-slate-800">Care Essentials</h1>
            <p className="text-xs text-slate-500">Your health knowledge hub</p>
          </div>
        </div>

        <div className="space-y-4">
          {/* Bone Health */}
          <SectionCard emoji="🦴" title="Bone Health">
            <p className="text-xs text-slate-600 leading-relaxed mb-3">
              After menopause, bone density naturally decreases. Here's how to protect your bones:
            </p>
            <div className="grid grid-cols-2 gap-2 mb-3">
              {[
                { emoji: "🥛", label: "1200mg calcium daily", desc: "Milk, ragi, sesame seeds" },
                { emoji: "☀️", label: "Vitamin D", desc: "15 min morning sunlight" },
                { emoji: "🏋️", label: "Weight-bearing exercise", desc: "Walking, light weights" },
                { emoji: "🚫", label: "Limit alcohol & soda", desc: "These weaken bones" },
              ].map((item) => (
                <div key={item.label} className="p-2.5 rounded-xl bg-amber-50/50 border border-amber-100">
                  <span className="text-lg">{item.emoji}</span>
                  <p className="text-[11px] font-bold text-slate-700 mt-1">{item.label}</p>
                  <p className="text-[10px] text-slate-500">{item.desc}</p>
                </div>
              ))}
            </div>
            {isPostmenopause && (
              <div className="p-3 rounded-xl bg-purple-50 border border-purple-200">
                <p className="text-xs font-semibold text-purple-800 flex items-center gap-2">
                  <Bone className="w-4 h-4" /> Consider a DEXA bone density scan
                </p>
                <p className="text-[11px] text-purple-600 mt-1">
                  Since you're in post-menopause, a DEXA scan can measure your bone density and help your doctor plan your bone health.
                </p>
              </div>
            )}
          </SectionCard>

          {/* Heart Health */}
          <SectionCard emoji="❤️" title="Heart Health" prominent={hasHypertension}>
            <p className="text-xs text-slate-600 leading-relaxed mb-3">
              Estrogen has a protective effect on the heart. As levels change, heart health deserves extra attention.
            </p>
            <ul className="space-y-2">
              {[
                "Monitor blood pressure regularly — aim for < 120/80",
                "Include omega-3 foods: flaxseeds, walnuts, fish",
                "Stay active — 150 minutes moderate exercise weekly",
                "Manage stress — try breathing exercises or yoga",
                "Regular cholesterol checks after age 45",
              ].map((tip, i) => (
                <li key={i} className="text-xs text-slate-600 flex items-start gap-2">
                  <Heart className="w-3.5 h-3.5 text-red-400 mt-0.5 flex-shrink-0" />
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
            {hasHypertension && (
              <div className="mt-3 p-3 rounded-xl bg-red-50 border border-red-200">
                <p className="text-xs font-semibold text-red-800">
                  ⚡ Since you have hypertension, regular BP monitoring is especially important.
                </p>
                <p className="text-[11px] text-red-600 mt-1">
                  Consider a home BP monitor and track readings weekly. Share with your doctor.
                </p>
              </div>
            )}
          </SectionCard>

          {/* Skin & Hair */}
          <SectionCard emoji="✨" title="Skin & Hair Care">
            <p className="text-xs text-slate-600 leading-relaxed mb-3">
              Hormonal changes can affect your skin and hair. Here's how to nurture them:
            </p>
            <div className="space-y-2">
              {[
                { emoji: "🥑", label: "Collagen-boosting foods", desc: "Bone broth, citrus fruits, berries, leafy greens" },
                { emoji: "💧", label: "Stay hydrated", desc: "8+ glasses of water daily for skin elasticity" },
                { emoji: "🧴", label: "Gentle skincare", desc: "Fragrance-free moisturiser, sunscreen SPF 30+" },
                { emoji: "💆", label: "Hair care", desc: "Biotin-rich foods (eggs, nuts), gentle shampoo, scalp massage" },
                { emoji: "🌙", label: "Night routine", desc: "Rich night cream, avoid hot water on face" },
              ].map((item) => (
                <div key={item.label} className="flex items-start gap-3 p-2.5 rounded-xl bg-pink-50/50 border border-pink-100">
                  <span className="text-lg">{item.emoji}</span>
                  <div>
                    <p className="text-xs font-semibold text-slate-700">{item.label}</p>
                    <p className="text-[11px] text-slate-500">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Sexual & Vaginal Health */}
          <SectionCard emoji="🌷" title="Intimate Health & Comfort">
            <p className="text-xs text-slate-600 leading-relaxed mb-3">
              Many women experience changes in intimate comfort during menopause. This is completely normal, and there are simple things that can help.
            </p>
            <div className="space-y-2">
              {[
                { emoji: "💧", label: "Stay comfortable", desc: "Water-based lubricants can make a real difference for dryness" },
                { emoji: "🧘", label: "Pelvic floor exercises", desc: "Kegel exercises strengthen pelvic muscles — even 5 minutes daily helps" },
                { emoji: "👗", label: "Cotton underwear", desc: "Breathable fabrics reduce irritation and keep you comfortable" },
                { emoji: "💬", label: "Talk openly", desc: "These changes are natural — don't hesitate to discuss with your doctor" },
              ].map((item) => (
                <div key={item.label} className="flex items-start gap-3 p-2.5 rounded-xl bg-rose-50/50 border border-rose-100">
                  <span className="text-lg">{item.emoji}</span>
                  <div>
                    <p className="text-xs font-semibold text-slate-700">{item.label}</p>
                    <p className="text-[11px] text-slate-500">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* HRT Information */}
          <SectionCard emoji="💊" title="About Hormone Therapy (HRT)">
            <p className="text-xs text-slate-600 leading-relaxed mb-3">
              Hormone Replacement Therapy can help manage menopause symptoms. Here's what to know:
            </p>
            <div className="space-y-2 mb-3">
              {[
                "HRT replaces estrogen (and sometimes progesterone) that your body produces less of",
                "It can help with hot flashes, night sweats, mood changes, and vaginal dryness",
                "HRT comes in different forms: tablets, patches, gels, and creams",
                "The best type and dose depends on your personal health history",
                "Benefits and risks vary by person — this is a conversation to have with your doctor",
              ].map((item, i) => (
                <p key={i} className="text-xs text-slate-600 flex items-start gap-2">
                  <Sparkles className="w-3.5 h-3.5 text-amber-400 mt-0.5 flex-shrink-0" />
                  <span>{item}</span>
                </p>
              ))}
            </div>
            <div className="p-3 rounded-xl bg-amber-50 border border-amber-200">
              <p className="text-xs text-amber-800 font-medium">
                💡 We're sharing this for awareness only — we never prescribe. Always discuss with your healthcare provider before starting any treatment.
              </p>
            </div>
          </SectionCard>

          {/* Warning Signs — RED border */}
          <SectionCard emoji="⚠️" title="When to See a Doctor Right Away" danger>
            <p className="text-xs text-red-700 leading-relaxed mb-3 font-medium">
              While most menopause symptoms are normal, some signs require immediate medical attention:
            </p>
            <div className="space-y-2">
              {[
                { symptom: "Chest pain or pressure", desc: "Could indicate a heart issue" },
                { symptom: "Severe or unexpected vaginal bleeding", desc: "Especially after 12+ months without periods" },
                { symptom: "Extreme mood changes or thoughts of self-harm", desc: "Please reach out to a helpline or doctor" },
                { symptom: "Sudden vision changes", desc: "Blurring, loss of vision in one eye" },
                { symptom: "Severe persistent headaches", desc: "New or different from usual headaches" },
                { symptom: "Unexplained weight loss", desc: "More than 5kg without trying" },
              ].map((item, i) => (
                <div key={i} className="flex items-start gap-3 p-2.5 rounded-xl bg-red-50 border border-red-200">
                  <AlertTriangle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="text-xs font-semibold text-red-800">{item.symptom}</p>
                    <p className="text-[10px] text-red-600">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Doctor Prep Tool */}
          <div className="bg-gradient-to-br from-amber-100 to-orange-100 rounded-2xl border border-amber-200 p-5 text-center">
            <div className="w-12 h-12 rounded-2xl bg-white/80 flex items-center justify-center mx-auto mb-3 shadow-sm">
              <FileText className="w-6 h-6 text-amber-600" />
            </div>
            <h3 className="text-base font-bold text-amber-900 mb-1">Doctor Prep Tool</h3>
            <p className="text-xs text-amber-700 mb-4 max-w-sm mx-auto">
              Generate a summary of your last 30 days of symptoms to share with your doctor. It's a great way to make the most of your appointment.
            </p>
            <button
              onClick={handleDownloadSummary}
              disabled={!profile}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-amber-500 text-white font-semibold text-sm shadow-lg shadow-amber-200/50 hover:bg-amber-600 active:scale-[0.98] transition-all disabled:opacity-40"
            >
              <Download className="w-4 h-4" />
              Download Symptom Summary
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
