import { useState, useEffect } from "react";
import { usePregnancyProfile } from "@/hooks/usePregnancyProfile";
import { useHealthLog } from "@/hooks/useHealthLog";
import { generateNutritionChecklist, NutritionChecklistItem } from "@/lib/nutrition/nutritionChecklistEngine";
import ScrollReveal from "@/components/ScrollReveal";
import ChecklistItem from "@/components/nutrition/ChecklistItem";
import ChecklistSummary from "@/components/nutrition/ChecklistSummary";
import AddChecklistModal from "@/components/nutrition/AddChecklistModal";
import { CheckSquare, Plus, Apple, ArrowLeft, Lightbulb } from "lucide-react";
import { Link } from "react-router-dom";
import { predictMaternityDeficiencies } from "@/lib/maternityNutritionEngine";

const STORAGE_KEY = "mama_haven_nutrition_checklist";

export default function NutritionChecklistPage() {
  const { trimester } = usePregnancyProfile();
  const { logs } = useHealthLog();
  
  const [items, setItems] = useState<NutritionChecklistItem[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<NutritionChecklistItem | null>(null);

  // Initialize and sync checklist
  useEffect(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    let currentItems: NutritionChecklistItem[] = saved ? JSON.parse(saved) : [];

    // Extract symptoms from logs
    const today = new Date().toISOString().split("T")[0];
    const recentLogs = Object.entries(logs)
      .filter(([date]) => new Date(date) >= new Date(Date.now() - 7 * 24 * 60 * 60 * 1000))
      .map(([date, entry]) => entry);
      
    const symptoms = recentLogs.flatMap(log => {
      if (log.phase !== "maternity" || !log.symptoms) return [];
      // log.symptoms is Record<string, boolean> for maternity
      return Object.entries(log.symptoms)
        .filter(([_, isActive]) => isActive)
        .map(([key]) => key);
    });
    // Get deficiencies
    const maternityData = predictMaternityDeficiencies(logs, trimester);
    const deficiencies = maternityData.predictions.map(p => p.nutrient);

    // Generate new suggestions
    const generated = generateNutritionChecklist(trimester, symptoms, deficiencies);

    // Merge: Keep all existing (custom + previously generated that user might have checked off)
    // Add new generated items if they don't exist by title
    const newItems = [...currentItems];
    generated.forEach(genItem => {
      if (!newItems.some(i => i.title.toLowerCase() === genItem.title.toLowerCase())) {
        newItems.push(genItem);
      }
    });

    setItems(newItems);
  }, [trimester, logs]);

  // Save to local storage whenever items change
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
  }, [items]);

  const handleToggle = (id: string) => {
    setItems(items.map(item => 
      item.id === id ? { ...item, completed: !item.completed } : item
    ));
  };

  const handleDelete = (id: string) => {
    setItems(items.filter(item => item.id !== id));
  };

  const handleSaveItem = (itemData: Omit<NutritionChecklistItem, "id" | "autoGenerated" | "completed">) => {
    if (editingItem) {
      setItems(items.map(item => 
        item.id === editingItem.id ? { ...item, ...itemData } : item
      ));
    } else {
      setItems([...items, {
        id: crypto.randomUUID(),
        ...itemData,
        autoGenerated: false,
        completed: false
      }]);
    }
  };

  const openAddModal = () => {
    setEditingItem(null);
    setIsModalOpen(true);
  };

  const openEditModal = (id: string) => {
    const item = items.find(i => i.id === id);
    if (item) {
      setEditingItem(item);
      setIsModalOpen(true);
    }
  };

  const incompleteItems = items.filter(i => !i.completed);
  const completedItems = items.filter(i => i.completed);

  return (
    <main className="min-h-screen bg-background pb-20">
      {/* Header */}
      <div className="border-b border-border bg-card/60 backdrop-blur-sm sticky top-0 z-10">
        <div className="container py-4">
          <Link 
            to="/nutrition"
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-3"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Nutrition Guide
          </Link>
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-purple-500 to-violet-400 flex items-center justify-center shadow-lg shadow-primary/10">
              <CheckSquare className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight">Nutrition Checklist</h1>
              <p className="text-sm text-muted-foreground">
                Smart nutrition actions personalized for your pregnancy journey.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="container py-6 max-w-3xl mx-auto space-y-8">
        <ScrollReveal>
          <ChecklistSummary items={items} />
        </ScrollReveal>

        <ScrollReveal delay={100}>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Lightbulb className="w-5 h-5 text-purple-600" />
              <h2 className="text-lg font-bold">Today's Focus</h2>
            </div>
            <button
              onClick={openAddModal}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 transition-colors"
            >
              <Plus className="w-4 h-4" />
              Add Task
            </button>
          </div>

          <div className="space-y-3">
            {incompleteItems.length === 0 ? (
              <div className="text-center py-10 bg-card rounded-xl border border-dashed">
                <Apple className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                <p className="text-muted-foreground text-sm">All caught up! Add a custom task or check back later.</p>
              </div>
            ) : (
              incompleteItems.map(item => (
                <ChecklistItem
                  key={item.id}
                  item={item}
                  onToggle={handleToggle}
                  onEdit={openEditModal}
                  onDelete={handleDelete}
                />
              ))
            )}
          </div>
        </ScrollReveal>

        {completedItems.length > 0 && (
          <ScrollReveal delay={200}>
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2 text-muted-foreground">
              <CheckSquare className="w-5 h-5" />
              Completed Summary
            </h2>
            <div className="space-y-3">
              {completedItems.map(item => (
                <ChecklistItem
                  key={item.id}
                  item={item}
                  onToggle={handleToggle}
                  onEdit={openEditModal}
                  onDelete={handleDelete}
                />
              ))}
            </div>
          </ScrollReveal>
        )}
      </div>

      <AddChecklistModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSave={handleSaveItem}
        initialData={editingItem}
      />
    </main>
  );
}
